server:
  port: 8081
  servlet:
    context-path: /api

spring:
  application:
    name: user-management-service
  datasource:
    url: jdbc:postgresql://localhost:5432/user_management
    username: dev@user_management
    password: password@user_management
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  liquibase:
    enabled: true
    change-log: classpath:db/migrations/changelog-master.xml
  cloud:
    config:
      enabled: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

springdoc:
  api-docs:
    path: /docs
