spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user_management
    username: dev@user_management
    password: password@user_management

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  config: classpath:log/logback-dev.xml